language: python

python:
  - "2.7"
  - "3.4"

script: python tests/starter.py

branches:
  only:
    - master
    
before_install:
    - pip install pytest pytest-cov

after_success:
    - coveralls
